:green_heart: Specify the kernel name explicitly
Unable to `quarto convert` because the kernel name `ruby3` not `ruby`:

```console
$ rake jupyter
quarto convert doc/qmd/preprocess_knock_Ruby-RedAmber.qmd -o
doc/notebook/preprocess_knock_Ruby-RedAmber.ipynb
ERROR: Jupyter kernel 'ruby' not found. Known kernels: python3, ruby3.
Run 'quarto check jupyter' with your python environment activated to
check python version used.
```

Since SciRuby/iruby#317, IRuby's default kernel name has been changed to
`ruby3` from `ruby`. However, we keep using `ruby` to respect Ruby's
strong compatibility.

Alternatively, we can modify the jupyter engine setting in qmd files
from `ruby` to `ruby3`:

```yaml
jupyter: ruby3
```

However, this approach requires updating all qmd files whenever Ruby's
major version changes. We don't want to pay that maintenance cost.